AllCops:
  Exclude:
    - 'db/schema.rb' # ignore generated schema
    - 'app/rpc/*' # ignore generated twirp code
    - 'rpc/*' # ignore generated twirp code
    - 'bin/*'

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  EnforcedStyle: single_quotes
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: true

Style/DocumentationMethod:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/ClassLength:
  Max: 180

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 23
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
    - 'spec/*.rb'

Lint/Loop:
  Enabled: true

Lint/Void:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*" # disable for rspec idioms
